name: Update badges

on:
  schedule:
    # Runs at 2am UTC
    - cron: "0 2 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: HunnTeRUS/HunnTeRUS@main
        with:       
          CREDLY_USER: otavio-santos.c3d92b14 # optional, but default will use the same from github
